### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by ScopeyNZ** [Germanaz0/laravel-ckan-api#2]
Hi there,

I'm interested in forking this module and making changes so it can be used outside of a Laravel context. Unfortunately there's no license and I'm not keen on making any changes without a license.

Is there any chance a license can be added?

**Comment by german-bortoli** [comment]
@ScopeyNZ  sorry for the late delay, somehow I missed the notification and was in vacation, yes offcourse, I will set this package with MIT license.

So you're free to go, regards.
